### PR TITLE
Fix metadatav14 event decoder

### PR DESCRIPTION
**Pull request by leonardocustodio**
Fix one more detail from: https://github.com/gmajor-encrypt/php-scale-codec/issues/5

### CODE REVIEW

**Comment by leonardocustodio** [comment]
Found another issue using another metadata. I will make a new commit soon.

**Comment by leonardocustodio** [comment]
@gmajor-encrypt can you check now if that's how you think it is supposed to work? This way it also solves this issue:
https://github.com/gmajor-encrypt/php-scale-codec/issues/5#issuecomment-1070336163

Have not yet checked the latest one that I found though.

**Comment by leonardocustodio** [comment]
This also fixes the issue but instead changed the metadatav14 parser, maybe that's what you expected @gmajor-encrypt ?
The thing is...... I tried a different metadata and even though it fixed the one before, this new one, gets into somekind of infinite-loop.

PS.: The same thing happens even if the other fix in the EventRecord instead. I'm submitting this new metadata so you can take a look as well.

**Comment by leonardocustodio** [comment]
Hey @gmajor-encrypt ,
This fixes all the issues from https://github.com/gmajor-encrypt/php-scale-codec/issues/5 and the infinite-loop. If it is not the way you expected feel free to make more improvements.

**Comment by gmajor-encrypt** [comment]
@leonardocustodio Thank you for your contribution, I have been busy recently, I will start to modify this part tomorrow

**Pull request merged**
